---
- name: Converge
  hosts: all
  tasks:
    - name: "Include iambryant.power.lpar and run configure_netboot_server.yml"
      ansible.builtin.include_role:
        name: iambryant.power.lpar
        tasks_from: configure_netboot_server.yml
