---
namespace: iambryant

name: power

version: 1.0.0

readme: README.md

authors:
  - iambryant

description: This collection includes roles for automating common tasks on IBM Power.

license:
  - MIT

license_file: 'LICENSE'

tags:
  - linux
  - power

dependencies:
  community.general: ">=8.0.0"
  ibm.power_hmc: ">=1.15.0"

repository: https://github.com/iambryant/ansible-collection-power

documentation: https://github.com/iambryant/ansible-collection-power

homepage: http://example.com

issues: https://github.com/iambryant/ansible-collection-power/issues

build_ignore: []
