lpar_os_version: "almalinux8"
lpar_mirror_url: "https://repo.almalinux.org/almalinux/8/BaseOS/ppc64le/os/"

lpar_web_root: "/var/www/html"
lpar_tftp_root: "/var/lib/tftpboot"

lpar_cloud_images: "{{ lpar_web_root }}/cloud-images"
lpar_seed_files: "{{ lpar_web_root }}/seed-files"
lpar_kickstart_files: "{{ lpar_web_root }}/kickstarts"

lpar_instances: []
