---
- name: "Ensure seed files are generated"
  delegate_to: "{{ groups['netboot'][0] }}"
  become: true
  block:
    - name: "Ensure UUID is generated"
      ansible.builtin.command: uuidgen
      register: system_uuid
      changed_when: false

    - name: "Ensure client meta-data file is present"
      ansible.builtin.template:
        src: "{{ item.os_type }}/meta-data.j2"
        dest: "{{ lpar_install_seed_files }}/{{ item.hostname }}/meta-data"

    - name: "Ensure client network-config file is present"
      ansible.builtin.template:
        src: "{{ item.os_type }}/network-config.j2"
        dest: "{{ lpar_install_seed_files }}/{{ item.hostname }}/network-config"

    - name: "Ensure client user-data file is present"
      ansible.builtin.template:
        src: "{{ item.os_type }}/user-data.j2"
        dest: "{{ lpar_install_seed_files }}/{{ item.hostname }}/user-data"
