---
- name: "Ensure netboot server is configured"
  delegate_to: "{{ groups['netboot'][0] }}"
  ansible.builtin.include_tasks: configure_netboot_server.yml
  apply:
    delegate_to: "{{ groups['netboot'][0] }}"
    become: true

- name: "Run logical partition installations sequentially"
  ansible.builtin.include_tasks: install_lpar.yml
  loop: "{{ lpar_instances }}"
