---
- name: "Check if VIOS logical partition {{ item.name }} already exists"
  connection: local
  ibm.power_hmc.vios:
    hmc_host: "{{ inventory_hostname }}"
    hmc_auth:
      username: "{{ hostvars[groups['hmc'][0]]['ansible_user'] }}"
      password: "{{ hostvars[groups['hmc'][0]]['ansible_password'] }}"
    system_name: "{{ item.system_name }}"
    name: "{{ item.name }}"
    state: "facts"
  register: vios_check

- name: "Run VIOS provisioning tasks"
  connection: local
  block:
    - name: "Ensure VIOS logical partition {{ item.name }} is present"
      ibm.power_hmc.vios:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: "{{ hostvars[groups['hmc'][0]]['ansible_user'] }}"
          password: "{{ hostvars[groups['hmc'][0]]['ansible_password'] }}"
        system_name: "{{ item.system_name }}"
        name: "{{ item.name }}"
        settings: "{{ item.profile_settings }}"
        state: "present"

    - name: "Install VIOS logical partition {{ item.name }} using the image available on the HMC"
      ibm.power_hmc.vios:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: "{{ hostvars[groups['hmc'][0]]['ansible_user'] }}"
          password: "{{ hostvars[groups['hmc'][0]]['ansible_password'] }}"
        system_name: "{{ item.system_name }}"
        name: "{{ item.name }}"
        image_dir: "{{ vios_install_image_dir }}"
        vios_iso: "{{ vios_install_vios_iso }}"
        vios_IP: "{{ item.install_settings.vios_ip }}"
        vios_gateway: "{{ item.install_settings.vios_gateway }}"
        vios_subnetmask: "{{ item.install_settings.vios_subnetmask }}"
        network_macaddr: "{{ item.install_settings.network_macaddr }}"
        prof_name: "{{ item.install_settings.prof_name }}"
        timeout: "{{ item.install_settings.timeout }}"
        action: install

    - name: "Ensure VIOS license is accepted"
      ibm.power_hmc.vios:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: "{{ hostvars[groups['hmc'][0]]['ansible_user'] }}"
          password: "{{ hostvars[groups['hmc'][0]]['ansible_password'] }}"
        system_name: "{{ item.system_name }}"
        name: "{{ item.name }}"
        action: accept_license

    - name: "Ensure VIOS firewall is enabled and allows required traffic"
      ibm.power_hmc.vios_secure:
        hmc_host: "{{ inventory_hostname }}"
        hmc_auth:
          username: "{{ hostvars[groups['hmc'][0]]['ansible_user'] }}"
          password: "{{ hostvars[groups['hmc'][0]]['ansible_password'] }}"
        system_name: "{{ item.system_name }}"
        vios_name: "{{ item.name }}"
        state: setting_firewall
        active: true
        reload: true
        ip_version: "ipv4"
        firewall_config:
          - port: 123
            present: allow
  when: vios_check.vios_info is not defined
  # Change this to take custom ports
